<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <OutputPath>../../artifacts/il2cpp/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../GameTweaks.Agent.Abstractions/GameTweaks.Agent.Abstractions.csproj" />
    <ProjectReference Include="../GameTweaks.Agent.Core/GameTweaks.Agent.Core.csproj" />
    <Reference Include="BepInEx.Core"><HintPath>../../vendor/il2cpp/core/BepInEx.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx.Unity.IL2CPP"><HintPath>../../vendor/il2cpp/core/BepInEx.Unity.IL2CPP.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
