name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  publish-release:
    name: Publish beta or stable release
    permissions:
      contents: write
    uses: ./.github/workflows/publish.yml
    with:
      release_tag: ${{ github.ref_name }}
      release_sha: ${{ github.sha }}
      development: false
    secrets: inherit
